# Generated by Django 2.0.7 on 2018-09-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHeld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_title', models.CharField(max_length=100)),
                ('end_title', models.CharField(max_length=100)),
                ('position_desc', models.CharField(max_length=10000)),
                ('duties', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=100)),
                ('company_desc', models.CharField(max_length=1000)),
                ('company_address', models.CharField(max_length=1000)),
            ],
        ),
    ]
