# Generated by Django 2.0.7 on 2018-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('date_aquired', models.DateField()),
                ('date_expired', models.DateField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=254)),
                ('school', models.CharField(max_length=254)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grad_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('info', models.TextField()),
                ('duties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('years_exp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PositionHeld',
        ),
    ]
