# Generated by Django 2.0.7 on 2018-10-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20181008_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certs',
            new_name='Cert',
        ),
    ]
