# Generated by Django 2.0.7 on 2018-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20181008_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='date_expired',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
