# Generated by Django 2.0.7 on 2018-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20181009_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
