# Generated by Django 2.0.7 on 2018-10-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20181009_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exp',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
