# Generated by Django 2.0.7 on 2018-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20181016_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('link', models.URLField()),
            ],
        ),
    ]
